### ISSUE TITLE
Can't get a markdown file to work

### ISSUE THREAD

**Issue by gschmutz** [e2fyi/minio-web#6]
Hi

First thanks for this useful tool, I have it working for HTML pages. 

But I can't make it work for Markdown files and I can't figure out what I might have done wrong. I have it running as a container in docker-compose with the following config

```yml
  minio-web:
    image: e2fyi/minio-web:v0.2.5
    container_name: minio-web
    hostname: minio-web
    labels:
      com.platys.name: minio-web
      com.platys.webui.title: Minio Web
      com.platys.webui.url: http://dataplatform:28306
    ports:
      - 28306:8080
    environment:
      MINIO_ENDPOINT: minio-1:9000
      MINIO_ACCESSKEY: V42FCGRVMK24JJ8DHUYG
      MINIO_SECRETKEY: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
      MINIO_SECURE: false
      MINIO_REGION: us-east-1
      EXT_BUCKETNAME: webapp-bucket
      EXT_PREFIX: my-web-app/
      EXT_DEFAULTHTML: myblog.html
      EXT_FAVICON: assets/myapp.ico
      EXT_LISTFOLDER: true
      EXT_LISTFOLDEROBJECTS: '*.{md,html,jpg,jpeg,png,txt}'
    volumes:
      - ./data-transfer:/data-transfer
      - ./custom-conf/minio-web/myapp.ico:/goapp/assets/myapp.ico
```

In Minio I have a file `MyMardown.md` inside `my-web-app`

```
$ docker exec -ti minio-mc mc tree --files minio-1/webapp-bucket/
minio-1/webapp-bucket/
└─ my-web-app
   ├─ MyMarkdown.md
   ├─ myblog.html
   └─ images
      └─ profile-picture.png
```

When I browse to `http://xxx.xxx.xxx.xxx:28306/MyMarkdown.md` I get the following error in the log

```bash
$ docker logs -f minio-web
{"level":"info","msg":"connecting to minio-1:9000"}
{"level":"info","msg":"bucket webapp-bucket: true"}
{"level":"info","msg":"object prefix: my-web-app/"}
{"level":"info","msg":"default index files: [myblog.html]"}
{"level":"info","msg":"default favicon: enabled"}
{"level":"info","msg":"caching: enabled"}
{"level":"info","msg":"list folder objects: *.{md,html,jpg,jpeg,png,txt}"}
{"level":"info","msg":"markdown rendering: enabled"}
{"level":"info","msg":"Listening to port: 8080"}
{"level":"info","msg":"Cache[/MyMarkdown.md] cached ok"}
{"level":"info","msg":"Cache[/MyMarkdown.md] cached ok"}
{"level":"error","msg":"Serve[/MyMarkdown.md] [500]: http: wrote more than the declared Content-Length"}
```

I have tried various other settings without success.....

Any idea?

Thanks
Guido
